import type { EventoCalendario } from '../types';

export const EVENTOS_CALENDARIO: EventoCalendario[] = [
  // JUNHO
  { id: 'c1',  data: '2026-06-06', titulo: 'Culto Fluir',                         tipo: 'especial',      horario: '19h30' },
  { id: 'c2',  data: '2026-06-07', titulo: 'EBD + Santa Ceia',                    tipo: 'santa_ceia',    horario: '9h / 18h' },
  { id: 'c3',  data: '2026-06-09', titulo: 'Terça Profética Brave',                tipo: 'especial',      horario: '20h' },
  { id: 'c4',  data: '2026-06-14', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c63', data: '2026-06-16', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c5',  data: '2026-06-18', titulo: 'Especial 20 Anos de Ministério',       tipo: 'especial',      horario: '19h', descricao: 'Pr. Eneas & Pra. Gisele' },
  { id: 'c6',  data: '2026-06-20', titulo: 'Encontro Plenas',                      tipo: 'especial',      horario: '19h30' },
  { id: 'c7',  data: '2026-06-21', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c64', data: '2026-06-23', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c8',  data: '2026-06-27', titulo: 'Encontro de Casais',                   tipo: 'especial',      horario: '19h30' },
  { id: 'c9',  data: '2026-06-28', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c65', data: '2026-06-30', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  // JULHO
  { id: 'c10', data: '2026-07-04', titulo: 'Culto Fluir',                          tipo: 'especial',      horario: '19h30' },
  { id: 'c11', data: '2026-07-05', titulo: 'Batismo + Santa Ceia',                 tipo: 'santa_ceia',    horario: '9h / 19h30' },
  { id: 'c66', data: '2026-07-07', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c12', data: '2026-07-12', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c67', data: '2026-07-14', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c13', data: '2026-07-17', titulo: 'Culto Valentes',                       tipo: 'especial',      horario: '20h' },
  { id: 'c14', data: '2026-07-19', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c15', data: '2026-07-19', titulo: 'Encontro Plenas',                      tipo: 'especial',      horario: '19h30' },
  { id: 'c68', data: '2026-07-21', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c16', data: '2026-07-26', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '18h', descricao: 'Aniversário Pra. Gisele' },
  { id: 'c69', data: '2026-07-28', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  // AGOSTO
  { id: 'c17', data: '2026-08-01', titulo: 'Culto Fluir',                          tipo: 'especial',      horario: '19h30' },
  { id: 'c18', data: '2026-08-02', titulo: 'EBD + Santa Ceia',                     tipo: 'santa_ceia',    horario: '9h / 18h' },
  { id: 'c70', data: '2026-08-04', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c19', data: '2026-08-09', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c71', data: '2026-08-11', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c20', data: '2026-08-15', titulo: '2ª Conferência da Honra',              tipo: 'especial',      horario: '19h' },
  { id: 'c21', data: '2026-08-16', titulo: 'EBD + Conferência da Honra',           tipo: 'especial',      horario: '9h / 18h' },
  { id: 'c72', data: '2026-08-18', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c22', data: '2026-08-20', titulo: 'Culto Valentes',                       tipo: 'especial',      horario: '20h' },
  { id: 'c23', data: '2026-08-23', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c73', data: '2026-08-25', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c24', data: '2026-08-29', titulo: 'Encontro de Casais',                   tipo: 'especial',      horario: '19h30' },
  { id: 'c74', data: '2026-08-30', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  // SETEMBRO
  { id: 'c75', data: '2026-09-01', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c25', data: '2026-09-05', titulo: 'Culto Fluir',                          tipo: 'especial',      horario: '19h30' },
  { id: 'c26', data: '2026-09-06', titulo: 'EBD + Santa Ceia',                     tipo: 'santa_ceia',    horario: '9h / 18h' },
  { id: 'c27', data: '2026-09-08', titulo: 'Terça Profética Brave',                tipo: 'especial',      horario: '20h' },
  { id: 'c28', data: '2026-09-11', titulo: 'Vigília IPAN',                         tipo: 'especial',      horario: '23h às 5h' },
  { id: 'c29', data: '2026-09-13', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c76', data: '2026-09-15', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c30', data: '2026-09-17', titulo: 'Culto Valentes',                       tipo: 'especial',      horario: '20h' },
  { id: 'c31', data: '2026-09-19', titulo: 'Encontro Plenas',                      tipo: 'especial',      horario: '19h30' },
  { id: 'c32', data: '2026-09-20', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c77', data: '2026-09-22', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c33', data: '2026-09-27', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c78', data: '2026-09-29', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c34', data: '2026-09-30', titulo: 'Worship Night',                        tipo: 'especial',      horario: '20h' },
  // OUTUBRO
  { id: 'c35', data: '2026-10-03', titulo: 'Music Talk Workshop',                  tipo: 'especial',      horario: '19h' },
  { id: 'c36', data: '2026-10-04', titulo: 'Aniversário IPAN SP + Eleições',       tipo: 'especial',      horario: '18h' },
  { id: 'c37', data: '2026-10-05', titulo: 'Aniversário IPAN SP',                  tipo: 'especial',      horario: '19h30' },
  { id: 'c79', data: '2026-10-06', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c38', data: '2026-10-11', titulo: 'Batismo + CM. Ágape',                  tipo: 'especial',      horario: '9h30' },
  { id: 'c39', data: '2026-10-12', titulo: 'IPAN Kids das Crianças',               tipo: 'especial',      horario: '' },
  { id: 'c80', data: '2026-10-13', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c40', data: '2026-10-15', titulo: 'Culto Valentes',                       tipo: 'especial',      horario: '20h' },
  { id: 'c41', data: '2026-10-18', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c81', data: '2026-10-20', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c42', data: '2026-10-25', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c82', data: '2026-10-27', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c43', data: '2026-10-30', titulo: 'Conferência Profetizando as Nações',   tipo: 'especial',      horario: '', descricao: 'Rio de Janeiro' },
  // NOVEMBRO
  { id: 'c44', data: '2026-11-01', titulo: 'EBD + Santa Ceia',                     tipo: 'santa_ceia',    horario: '9h / 18h' },
  { id: 'c83', data: '2026-11-03', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c45', data: '2026-11-07', titulo: 'Culto Fluir',                          tipo: 'especial',      horario: '19h30' },
  { id: 'c46', data: '2026-11-08', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c47', data: '2026-11-10', titulo: 'Terça Profética Brave',                tipo: 'especial',      horario: '20h' },
  { id: 'c48', data: '2026-11-15', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c84', data: '2026-11-17', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c49', data: '2026-11-19', titulo: 'Culto Valentes',                       tipo: 'especial',      horario: '20h' },
  { id: 'c50', data: '2026-11-21', titulo: 'Encontro Plenas',                      tipo: 'especial',      horario: '19h30' },
  { id: 'c51', data: '2026-11-22', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c85', data: '2026-11-24', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c52', data: '2026-11-29', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  // DEZEMBRO
  { id: 'c86', data: '2026-12-01', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c53', data: '2026-12-05', titulo: 'Culto Fluir',                          tipo: 'especial',      horario: '19h30' },
  { id: 'c54', data: '2026-12-06', titulo: 'EBD + Domingo da Visão + Santa Ceia',  tipo: 'santa_ceia',    horario: '9h / 18h' },
  { id: 'c55', data: '2026-12-08', titulo: 'Terça Profética Brave + Confra Mulheres', tipo: 'especial',   horario: '20h' },
  { id: 'c56', data: '2026-12-12', titulo: 'Ensaio Geral Musical',                 tipo: 'especial',      horario: '20h' },
  { id: 'c57', data: '2026-12-13', titulo: 'Culto da Família',                     tipo: 'culto_regular', horario: '18h' },
  { id: 'c87', data: '2026-12-15', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c58', data: '2026-12-16', titulo: 'Ensaio Geral Musical',                 tipo: 'especial',      horario: '20h' },
  { id: 'c59', data: '2026-12-17', titulo: 'Culto Valentes + Confrai',             tipo: 'especial',      horario: '20h' },
  { id: 'c60', data: '2026-12-18', titulo: 'Ação de Natal',                        tipo: 'especial',      horario: '20h' },
  { id: 'c61', data: '2026-12-19', titulo: 'Musical de Natal',                     tipo: 'especial',      horario: '19h30' },
  { id: 'c62', data: '2026-12-20', titulo: 'Musical de Natal',                     tipo: 'especial',      horario: '19h30' },
  { id: 'c88', data: '2026-12-22', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
  { id: 'c89', data: '2026-12-27', titulo: 'EBD + Culto da Família',               tipo: 'culto_regular', horario: '9h / 18h' },
  { id: 'c90', data: '2026-12-29', titulo: 'Terça Profética',                      tipo: 'culto_regular', horario: '20h' },
];
